### ISSUE TITLE
Editorial review

### ISSUE THREAD

**Issue by davidpesce** [AICC/CMI-5_Spec_Current#162]
There seem to be quite a few editorial/grammar mistakes still within the master branch. I'm guessing this was due to the merge. Would it be easier for me to create a merge-able branch for both the runtime and coursestructure files?

**Comment by andyjohnson** [comment]
Hey @davidpesce , we had a merge issue and since the entire PR needed to be looked at anyways, I took a shot at integrating the mistakes on the fly.  Thanks so much for the work you did!  I did notice that there were still a good amount of stray CMI-5s and other issues.  One comment I will make is that too many "the"s were inserted.  Sometimes we do speak generically about LMSs, activities, etc.  I tried to use my best judgment on these.  At this point if you still want to hit some of them, you should create a new branch off the master and make the changes there so we can decide to merge them.
