### ISSUE TITLE
Prevent AU's from Voiding cmi5 specific statements

### ISSUE THREAD

**Issue by MrBillMcDonald** [AICC/CMI-5_Spec_Current#202]
Because most training in an LMS use case is for compliance, AU (content) should NOT be allowed to Void any "cmi5" specific statements.  The rationale for this is that the content/use could "game the system" in high stakes training.  Also voided cmi5 statements could interfere with sequencing (moveon) rules.

LMS can still void cmi5 statements based on business policy.

This additional requirement should be considered post sandstone after vendor comment.

**Comment by andyjohnson** [comment]
Per the 5/29/15 call, in the xAPI spec, there is discussion/language that voiding should require a higher level of permissions than AUs would have.  Issue really comes in what is allowed to be voided - anything with the cmi5 category tag?  Seems bad because then we may over-restrict use of cmi5 category tag.  The moveon tag may not be sufficient.  Best done as "the LMS will not provide permissions/credentials which allow the AU to issue voiding Statements"

**Comment by andyjohnson** [comment]
Add to section 6.0 if approved.  The returning of a 403 will be expected by xAPI, but isn't necessary to mention in this spec.
