### ISSUE TITLE
XSD allows Mastery Score to be optional, but description indicates it is mandatory

### ISSUE THREAD

**Issue by jamie-burns** [AICC/CMI-5_Spec_Current#203]
In **7.1.4 AU Metadata** (Course Structure), the Mastery Score is listed as a Required attribute, but the XSD allows for this attribute to be omitted -

    <xs:attribute name="masteryScore" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:decimal">
          <xs:minInclusive value="0"/>
          <xs:maxInclusive value="1"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>

**Comment by svrnm** [comment]
I think this is an similar issue like #157 - this is a switch of two kind of requirements:  the LMS has to support the masteryScore - as stated in the runtime specification and the course structure has to provide a masteryScore. Since this should be the second and since the masteryScore can be empty (i.e. "an empty string"), the requirement should be set to "No" and furthermore the value "empty string" can be removed since this is an leftover as we changed from an element to an attribute.

**Comment by jamie-burns** [comment]
Should be covered in pull request #206

**Comment by andyjohnson** [comment]
Merged PR #206 - closing
