### ISSUE TITLE
Explain the vision

### ISSUE THREAD

**Issue by mrft** [AICC/CMI-5_Spec_Current#230]
Hi,

I stumbled upon this today, because I am slowly getting an understanding of some of the things that are wrong with SCORM.

So, if this project is aiming to be 'the new SCORM', it would need to make sure that the mistakes made in SCORM are not made again.

What I am missing here is a general *vision* of what this new standard should become. What is the reasoning behind all this.

* What exactly is this standard trying to solve? What use cases do you have in mind?
* And what is it explicitly NOT trying to solve (and why)?
* Why are you defining a new standard in the first place? What are the errors in SCORM that you are going to avoid, and how will you do this? (It would be nice to have a list of 'flaws in SCORM', each with an answer on how the new standard will solve that problem)
* Why did you make the choices you made? (for example, you chose xml as a format, but you should be able to defend that choice when somebody comes along an says: 'why not use JSON?')
* What are the consequences on a technological level? Also think about a possible implementation, and the problems that will need to be solved. If you write a nice standard that is extremely hard to implement, and no one even writes a reference implementation, it might take a long time before it is actually being picked up (look at xslt2.0 for example)
* How does it fit in a world full of mobile devices and apps?
* ...

I think it is because people can ask those 'why' questions, that things - that may have been overlooked the first time - are brought to your attention. (I suppose that you didn't put this publicly on github because you don't want other people to share their thoughts?)

**Comment by MrBillMcDonald** [comment]
mrft,

We discussed your post at our August 7th meeting, and you are correct in that we do not have background information about "why" we are doing cmi5 (and what it will accomplish) on the GitHub repo.  

While there have been several presentations and articles made this topic by our participants recently, we have not re-established a website presence due to the transition of this activity from the AICC last year to the ADL.  The ADL is currently in the mist of restructuring its website and will publish cmi5 background information there soon.  

In the meantime, the "why cmi5" questions you have raised are important and visitors to this GitHub repository should be able to see something that explains what we are doing.  To that end we plan to update the README on this GitHub repo to provide background information on what cmi5 is and why we are doing it.  

While you are waiting for the README to be updated, please feel free to look at the following links on cmi5.  They might help to answer those questions:

* cmi5: The next generation SCORM ( http://risc-inc.com/blog/the-next-generation-scorm-cmi-5/ )
* cmi5 Process Flow: An overview (http://risc-inc.com/blog/cmi-5-overview-process-flow/)
* cmi5: xAPI for LMSs ( http://www.slideshare.net/BillMcDonald3/cmi5xapicamp-50890282 )
* cmi5: The Bill McDonald Interview ( https://www.youtube.com/watch?v=KKbhLqBVpPE )

Please note that this is a volunteer community effort.  **We very much want to encourage people to share their thoughts about cmi5.**  You are welcome to make comments here and also participate in the weekly Web Conferences that are open to all.  (See the Wiki for this GitHub - we would love to see you there !)

Sincerely,

Bill McDonald
cmi5 working group leader

**Comment by mrft** [comment]
Last Friday, when trying to join the web meeting, I sent an email to C. Wiggins, but I got no answer so far.

I am hoping to be able to participate properly this week...

**Comment by MrBillMcDonald** [comment]
mrft,

Please use the following URL to register for the GotoMeeting Web conference.

Registration URL: https://attendee.gotowebinar.com/register/9089690481445095682

Sincerely,

Bill McDonald

**Comment by mrft** [comment]
I wasn't able to join last Friday, but I will try to be present this
Friday. (Hopefully the audio will work if I use firefox)

2015-08-20 18:41 GMT+02:00 Bill McDonald <notifications@github.com>:

**Comment by MrBillMcDonald** [comment]
Document describing CMI5 overview, scope, advantages, SCORM comparision will address these questions.  Document for gitHub repo is pending
