### ISSUE TITLE
Multiple Passed and Failed Statements in a AU Session 

### ISSUE THREAD

**Issue by MrBillMcDonald** [AICC/CMI-5_Spec_Current#262]
(When PassIsFinal is set to False)  If an AU issues multiple Passed and Failed statements within an AU session, what determines the final result.  The last statement issued ?

What the implications for a registration ?  (Multiple AU sessions)  Can a user go back and Fail a passed AU (causing a "status reversal") ?

**Comment by liveaspankaj** [comment]
Very interesting question. What are the use cases that required this "constant" PassIsFinal

**Comment by davidpesce** [comment]
Is there anything to stop the AU from creating a new session (from within itself) to allow a user multiple "attempts" at passing an assessment? If not, would this be frowned upon?

The only use-case I can come up with (and I'm grasping for straws at this point), is when course navigation is locked. Meaning users have to take the content portion of the course until they unlock the assessment. If we require a user to relaunch an AU in order to get another grade (pass/fail), they'd have to go through the content and then assessment again. Such a small use-case, but may be worth discussing. Especially if the solution is for the AU to create a new session from within itself.
