### ISSUE TITLE
What does issuing a statement "before" and "after" mean?

### ISSUE THREAD

**Issue by garemoko** [AICC/CMI-5_Spec_Current#295]
Sorry if this is covered somewhere already. In a few places cmi5 talks about obligations or restrictions regarding issuing statements before or after one another.

Does this relate to 'stored' or 'timestamp'? (I would hope it's timestamp as 'stored' can change between LRSs)

If timestamp, is it OK to send multiple statements using the same timestamp, where one of those is supposed to be "after" another in the group? E.g. the learner gets to the end of the course, they pass, complete and terminate all at the same time.

**Comment by MrBillMcDonald** [comment]
Andrew,

Thanks for raising this issue ! 

We discussed your issue at today's meeting (Oct 23) meeting at length.  We do not have consensus on this yet and will discuss if further.

The group agrees that we need more clarification around determining/enforcing the order of statements.  The current thinking (among some in the group) is that "timestamp" will be used to determine order if the order that statements are received is ambiguous.  

More to follow next week.

Sincerely,

Bill McDonald

**Comment by bscSCORM** [comment]
@garemoko regarding `stored` changing between LRSs, that doesn't matter here because all the obligations cmi5 discusses are regarding the communication of an AU to a particular LMS. So when we talk about `stored` in that context, we're talking about the time the LMS receives and process the statement.

There are some ways in which using `stored` would be beneficial:
* it's immediate, the LMS can rely on the session being over when a `.../terminated` statement is received, and perform rollup. (vs, when the `.../terminated` is received, the LMS has to hold the session open for ... how long? and wait for other statements, possibly even the `.../initialized` statement, and eventually decide the session is over, how?)
* sequence based feedback for the AU is possible -- (due to the immediacy above), the LMS can actually reject other statements it receives before an `.../initialized`, for example. Feedback is important, because it's very confusing for a content author to have statements ultimately `void`-ed as invalid that are initially accepted. (Of course some feedback is still possible, if an AU actually sends an `.../initialized` statement with a timestamp in the future, and then sends other statements with earlier timestamps, those could be rejected. But in the more likely case the content author simply forgot to send the `../initialized`, the LMS has to assume it might be coming later (but with an earlier timestamp).
* ultimately stored time does matter, it's just a question of how large the window is. Some period of time after receiving a `.../terminated`, we have to actually shut down the session. The question here is probably whether that window is milliseconds, seconds, minutes, or more.

And there are some ways that using `timestamp` would be beneficial
* `stored` isn't as easy as it sounds. We have to consider the case that the LMS is a distributed system that might get slightly confused about the actual arrival time of statements, so that statements that arrive in rapid succession might get reversed.
* The AU doesn't have to take steps to make sure the statements are sent in the correct order. For example, the AU can fire off the `.../initialized` statement, not wait for an acknowledgement, and send more statements.

It seems to me that the biggest reason to use `timestamp` is to avoid giving the AU more responsibility. However, I think we can avoid additional requirements and rather just lay out best practices. We could use `stored` and say that the LMS _may_ take into account some window to allow for out-of-order processing of threads or a reasonable delay for TCP re transmit or even a full retry from the client.

**Comment by MrBillMcDonald** [comment]
Andrew,

Per today's meeting (Oct 30) discussion with Ben (which happened after his post), here is my response to your questions:

**Q1. Sorry if this is covered somewhere already. In a few places cmi5 talks about obligations or restrictions regarding issuing statements before or after one another. Does this relate to 'stored' or 'timestamp'? (I would hope it's timestamp as 'stored' can change between LRSs)**

_A1. We are revising our language on the "order of statements". The current thinking is that Timestamps will not be used by the LMS to validate/enforce these rules as they are "too expensive" for little benefit.  The only ordering/timing rule enforced by the LMS will be to prevent the recording of statements after a Terminated Statement is received.  The LMS will then wait  "a specified period of time" after which it will reject any new statement for that session.  (the "period of time" is LMS/LRS specific)_

**Q2. If timestamp, is it OK to send multiple statements using the same timestamp, where one of those is supposed to be "after" another in the group? E.g. the learner gets to the end of the course, they pass, complete and terminate all at the same time.**

_A2. The timestamps do not have to be unique.  It is recommended that timestamps be made when the action actually happened.  (forcing them to be unique would create artificial time differences which were seen as necessary)   If the statements "happen at the same time" it is also recommended that they be batched in single post._

**Comment by MrBillMcDonald** [comment]
Closed Per Issue #297 resoultion
