### ISSUE TITLE
cmi5 Statement Sequencing Issues (Per Oct 23 Meeting)

### ISSUE THREAD

**Issue by MrBillMcDonald** [AICC/CMI-5_Spec_Current#297]
Per the Oct 23rd cmi5 working group meeting, we will discuss how to determine and enforce statement sequence/order for required cmi5 statements.  In order to better organize next week's discussion, the group will limit its discussion to proposals/positions on the following statement sequencing topics:

 * **Topic 1** - If the LMS/LRS can determine the order as they statements arrive the it should use "actual order".

*  **Topic 2**  - LMS/LRS should use the (AU) time stamp if it is ambiguous as to when the statements have arrived. (ultimate ordering)

* **Topic 3**  - If the AU cannot get an acknowledgement in a timely manner then it can resend the previous statement batched together with the subsequent required statement (in the correct order).

* **Topic 4** - Required (AU) statements must be in a specific order by timestamp

* **Topic 5** -  No Required (AU) statements can share the same timestamp

_Please post your proposal/position on these topics on the GitHub Issues list BEFORE the next meeting on Oct 30 (10:30am Eastern US time).  You will need to be present on the [cmi5 GotoMeeting](https://attendee.gotowebinar.com/register/9089690481445095682) to answer clarifying questions._

**Comment by jhnsntmthy** [comment]
We have talked about this internally at my company, where we have experienced issues in the past playing statements into an LRS from an "occasionally-connected" devise (read spotty-internet-connection). What we would like to see in the CMI-5 spec is to have a timestamp per-recorded-activity that would be unique to the user and the AU (no AU statements can share the same user/activity/timestamp).

On the LMS/LRS side, receiving a statement with a user/activity/timestamp that already exists would be thrown away, thus eliminating duplication.

There will always need to be some error-connection-handling on the client side in the case of a poor network connection, but statements could pile up throughout the AU and post when the connection is solid. A batch that is sent and receives a success message from the LRS could clear out the buffered messages.

One other use case we have talked about in the past is data portability between LRSes. We want to be able to capture CMI5 messages and then at a later time (days, weeks or months) be able to "replay" them to another LRS on behalf of the user, to share his data with another system (usually at the user's request), and having a timestamp be received and put in the proper sequence-of-events by the receiving LRS would be vital to this functionality.

**Comment by jhnsntmthy** [comment]
One of our other methodologies is to be able to use a message queue service as a middleman between client and the LRS. In a proper SOA environment, the messages would "fire and forget" to the message queue, and the message queue would ensure delivery to the LRS. In the case of severe latency or server outages, having a timestamp is important. 

We often have learners who try to complete their course last-minute before a certification deadline, and we have to prove that their activity was done by a specific timestamp. We want this to be as fault-tolerant as possible.

**Comment by fugu13** [comment]
Speaking just about the duplication issue, you can guarantee lack of duplication for a given Statement send if you generate a Statement ID (a UUID) for the Statement before attempting send. LRSs are required to only store the first Statement they see with a given ID. I strongly recommend it for any production system, since any connection can have occasional "uncertain response" situations, even quite reliable ones, and most aren't quite reliable.

For more specialized situations, such as if the same Statement would be generated by multiple systems, or to avoid having to store a a history of "possibly sent" statements when you might want to resend bulk data, you can even go so far as to use a deterministic algorithm to construct your Statement IDs (see versions 3 and 5 of the UUID spec) based on an application-specific namespace plus the uniqueness-determining parts (in your example, actor+object+timestamp).

**Comment by MrBillMcDonald** [comment]
See Oct 30th Meeting Minutes - https://github.com/AICC/CMI-5_Spec_Current/wiki/CMI-5-Working-Group-Meeting-Minutes-%E2%80%93-October-30th,-2015

**Comment by MrBillMcDonald** [comment]
Closed per Pull Request #384
