### ISSUE TITLE
Changing PURL.org

### ISSUE THREAD

**Issue by andyjohnson** [AICC/CMI-5_Spec_Current#353]
So I know it hasn't been long since we implemented purl.org as a portion of our identifiers with the idea of it being "stable", but our stability is now not stable, so a switch to w3id is probably for the best.  Here is a synopsis (thanks, Jason, who has been following the vocab effort very closely):

1) PURL.org is no longer allowing new PURLS to be created or old ones to be updated. Login is temporarily disabled.
2) The W3C has started a service to solve this problem long term, https://w3id.org and PURL.org is recommending everyone to use their service instead for all new IRIs.
3) https://w3id.org is synchronized with github, making the process really simple to generate new IRIs. In addition, their server at https://w3id.org is configured to handle content negotiation. This means you don’t have to do anything except host the HTML and other machine readable metadata (RDF) at your server. The process and repo is at the following link, and simply involves updating a .htaccess file specifying your target URL for each IRI. https://github.com/perma-id/w3id.org.

Hopefully we can discuss this Friday.  Thanks!

**Comment by bscSCORM** [comment]
Using URLs actually resolve is "nice to have", using existing URIs once they have been coined is crucial. The spec may not be at 1.0 yet, but we chose to put real identifiers in place rather than "example.org" indicating we were still deciding, so we have a commitment to live up to. https://w3id.org may be a fine place to coin new identifiers, but for the same reason we didn't coin new verbs for verbs like `http://adlnet.gov/expapi/verbs/launched`, we shouldn't coin new identifiers for any of our `http://purl...` identifiers either.

These identifiers are all well-defined in cmi5 itself, so resolvability is even less important than usual.

I suggest we table this discussion until we need to define new identifiers, and then we can decide the best scheme with which to name them.

**Comment by andyjohnson** [comment]
I don't want to change the adlnet.gov core IRIs, as those are a de-facto part of xAPI.  However, for cmi5 defined IRIs, we went with PURL identifiers, which now seems to steer people in the wrong direction.  A lot has changed in this version, so I suggest we move these IRIs to something with more life than purl.org.  I worry we are setting a bad example at this point with the purl identifiers.

**Comment by andyjohnson** [comment]
Per the 12/11/15 call, resolvability is a “nice-to-have”.  We are worried about setting a bad practice.  Jason Haag from ADL joined to discuss long-term w3id plans.  The purl.org IRIs will actually be okay as W3C will own them and maintain them.  The easier to use presence will be under w3id, so new IRIs should use these.  The question now is do we steer people towards the easier to use w3id at the expense of any early adoption of the PURL IRIs.

**Comment by cawerkenthin** [comment]
We've already got two domains in our verbs; I'd hate to have 3.  While @bscSCORM 's argument about changing them after Sandstone is a good one, I think the idea of having consistent place to put new IRI's carries more weight.  It's now or never...

**Comment by MrBillMcDonald** [comment]
Per Jan 15 meeting.  Will change Purl IRI's to W3C IRI's.  Rationale - more appropriate for an xAPI profile ( Like cmi5) and W3C will have greater longevity.
