### ISSUE TITLE
Explicitly allow the LMS to override the "masteryScore" as defined in the course structure

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#378]
See #359 for more. Specifically the verb section calls out that the pass/fail determination is based on the value in the course structure, but needs to be based on the value in the LMS launch data.

There also needs to be a requirement explicitly stated that allows the LMS to provide a non-course structure provided value in the LMS launch data.

**Comment by bscSCORM** [comment]
I'm not sure we _did_ agree that the LMS could override the mastery score, not exactly anyway, @cawerkenthin . We do have the requirement:
> The LMS SHOULD provide a user interface to the LMS administrative users to create and edit course structures internally.

And from that requirement it follows that the Mastery Score the AU receives might not be the Mastery Score that was in the course structure the LMS originally imported. The AU is required to act on what's in the launch/state data, not on what's in the course structure. We probably should remind AU authors that they can't assume to know what's in the course structure within the runtime of the AU, since it may have been edited.

This doesn't imply any specific requirement about Mastery Score to me though.

**Comment by bscSCORM** [comment]
To restate the above, I don't think the LMS can actually "ignore" or "override" the course structure, but it can edit it -- which to the AU will look very much like it did ignore or override the course structure.

**Comment by brianjmiller** [comment]
Does edit in that case imply a new course id?

**Comment by bscSCORM** [comment]
That's a good question. I don't think there is a clear answer in the spec as it stands, nor do I recall us even discussing the issue before. We say the course ID has to be "unique", but what do we mean by that? We probably need some language around what is a permissible edit to an existing course vs a "new course".

**Comment by cawerkenthin** [comment]
After I joined the committee nearly 3 years ago, one of the first things we discussed was that the LMS Administrator knew their business better than the content developer.  As a result, we decided that the LMS could edit the imported structure.  Specifically we discussed changing the mastery score and the reasons for doing so.  I am surprised this is resurfacing so late.  We should perhaps examine what items the LMS could not edit, but I see no reason it could not change the ID.

**Comment by bscSCORM** [comment]
@cawerkenthin I'm not suggesting the mastery score can't be edited -- as you say, we've been planning on that for a long time. I do wonder, if it is edited, is it the same course or should the LMS also have to change the course ID? I figure it's probably the same course, but we should spell it out.

**Comment by cawerkenthin** [comment]
About the only things I would not allow the LMS to override is url, launchMethod, authenticationMethod, launchParameters.

**Comment by MrBillMcDonald** [comment]
Closed per Jan 15th Meeting

**Comment by MrBillMcDonald** [comment]
Per Jan 29 meeting.   Add 

13.2 LMS Course Structure Requirements
The LMS MAY override the following AU metadata elements at runtime:
•	masteryScore
•	moveOn
The LMS SHOULD have an editor to modify course structures. If the LMS modifies the course structure, it MUST create a new instance of the course structure with a different id.


and

6.1 Course Structures
•	The LMS SHOULD implement a means to create, edit, and maintain course structures.

**Comment by cawerkenthin** [comment]
I do NOT agree that the LMS must  make a new course simply because it modified the masteryScore. We have many instances of a course that requires different scores for different groups of people.  Now I have to make them separate courses?  That's nuts.

**Comment by cawerkenthin** [comment]
Example:  We have a customer that requires Instructors to re-take a course every 2 years to maintain their instructor status.  They must get 100 on all AU's in the course.  Students, however, need only an 80 for the exact same course.

**Comment by brianjmiller** [comment]
@cawerkenthin we tried to capture your thoughts via:

> The LMS MAY override the following AU metadata elements at runtime:

Does that not work for you? Perhaps we need to be more specific about "runtime"?

The others are shoulds around providing course editing which was already implied, and that if one does edit a course structure it must have a new id.

**Comment by cawerkenthin** [comment]
No, this statement is the problem.

If the LMS modifies the course structure, it MUST create a new instance of the course structure with a different id.

**Comment by brianjmiller** [comment]
How do you keep track which course is which without a PK to distinguish or to compare against another system that has a course with the same id? You have to have some other system specific knowledge, such as the role, to distinguish, which can just as easily be generated on the fly at runtime by the system as it is stored. Certainly within your own system if you want to cache an altered course structure with additional pieces to a pseudo-PK that would be fine, but as soon as you go to export multiple course structures with additional PK components you have to serialize them to get uniqueness. Without this I don't see how you could track a course structure without hashing together all of the data pieces within the course structure itself.

**Comment by cawerkenthin** [comment]
@brianmiller,
What is the argument that we need an entirely new  course every time we modify the masteryScore or moveOn?

**Comment by bscSCORM** [comment]
@cawerkenthin first of all, I agree it's silly to require a new time `masteryScore` or `moveOn` is modified. But I think what @brianjmiller is getting at is for a course structure ID to mean anything, we have to have some clear definition around what can be changed while keeping the same ID, and it's not currently clear that `masteryScore` and `moveOn` are special in that regard.

Perhaps if we expect that the same course structure will be assigned different `masteryScore` and `moveOn` at runtime, we should rename these to `defaultMasteryScore` and `defaultMoveOn`, and ensure we talk about runtime values from the LMS in the AU requirements rather than the course structure (we should anyway), _and_ ensure that the actual runtime values used are stored in some statement (possibly the launch statement), so that it's clear to anyone looking at the statement stream what values were in force.

In any case, we need a discussion around what can and can't be changed within a course structure and have it logically remain "the same course structure".

**Comment by cawerkenthin** [comment]
@bscSCORM, your idea of using "default", with language indicating that it can be overridden at runtime is a good one.

However, consider the scenario.  You have a 40 AU course and discover that one AU has the incorrect masteryScore (default or otherwise).  So the LMS Admin makes an edit to fix it.  Now the LMS "MUST" make a new course?  Why are we placing requirements on the LMS... this language seems to require course versioning?  It seems to me this is either a feature the LMS has or does not, and it is not the job of the cmi5 committee to specify LMS features that really have no impact on cmi5 itself.  I believe this is out of our scope.

**Comment by bscSCORM** [comment]
I could certainly see making an exception for `default`.... values because we've explicitly called them out as something that might change.

I suggest that we have to draw a line somewhere, and should be discussing where that line is. But I suppose that idea that "we have to draw a line somewhere" needs examination.

So, consider the case where we don't draw a line as to what level of editing a course creates, in effect, a new course. That would mean that an LMS would be free to churn out packages that contained completely unrelated sets of AUs and tag them with the same course ID, and there would be no requirement in the spec to say otherwise. And, we've already agreed to some informative language that _strongly implies_ we're not OK with that: https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#id

> A globally unique IRI for the course. Used to explicitly identify the course instance.

The above indicates we expect that a single course IRI will refer to a particular course structure, and not some other course structure.

Now it may be that even if we draw a line, that line will be impractical to enforce. If so, it calls into question in my mind whether we should even have an ID. What about saying something like this:

> An LMS MUST NOT maintain more than one definition of a course structure with the same course ID.

I think the above is the very least we should do -- I still have concerns about editing, consider the case where a content provider has released a course about disarming explosives, with a course id of `http://example.org/disarmingexplosives` , and then my LMS administrator uses that package as an example, puts in AUs about basket weaving instead. Now statements about that propagate to another system, which spits out a report: "Ben has had training in how to disarm explosives", as it would reasonably do if it had a copy of the original package. That seems like it would be bad.

So, perhaps what we should be looking at for a requirement would be more like:

An LMS, or any system that has a copy of a course structure, `MAY` ignore any other definitions of that structure with the same ID it sees, and assume that the copy it already has is correct.

If we're not willing to say the above, then we should probably just get rid of the ID, because it has no function.

**Comment by brianjmiller** [comment]
I'll just add that by virtue of adding that id to the "Satisfied" statement in the 'object' we're accepting what it means for that object to have that id in xAPI terms as well as LMS/cmi5 terms which is where my original argument comes from and I think is the core principle of what @bscSCORM is building on. Ultimately it comes down to do we equate in xAPI terms two statements with the same `object.id` for what amounts to at least in minimal terms two different things. Hence the need to draw the line, just how different do we tolerate for equality.

**Comment by brianjmiller** [comment]
And as we've seen with certain content authoring tools, it is *much* easier to loosen the requirements later, but near impossible to roll that back. We are better off erring on the side of caution and strict interpretation and determining that it needs to be loosened for adoption, then the opposite.

**Comment by cawerkenthin** [comment]
@bscSCORM I think trying to stop an malignant LMS Administrator is an impossible task.  With existing standards (SCORM included), I can easily rename a course "Bomb Diffusing" even though the SCORM module is about making a PowerPoint presentation.

However, in this case we are talking about changing the passing score... I hardly see how that is significant enough to make a new course because we are writing that passing score into the LRS, in which statements are immutable.  We have a record of the change and the course is not materially altered.  In my case, the majority of my clients will be raising the passing score, not lowering it, because "80% of Don't Blow Up The Place" is not acceptable.

**Comment by davidpesce** [comment]
I agree with @cawerkenthin. There are many cases where we've had to modify the passing score in the LMS after the course has already been published and posted to the LMS. Requiring it to go back to the content developer is unnecessary and in some cases impossible.

**Comment by brianjmiller** [comment]
Except that use case is still *runtime* and has nothing to do with the supposed "edit" feature, where presumably "edit" is intended to tie together with "export". So if one LMS administrator wants to say everyone passes all the time then that is fine at runtime, but do you want that administrator exporting courses that way? That have the same identifier as a course that you require a 100% on?

All of the "edit" and "export" requirements are SHOULDs and perhaps we ought to be talking about whether they should be in there at all? There is very little that can stop an LMS from doing virtually anything at runtime, including inserting additional AU requirements, etc. but presumably the intention of having an identifier in the course at all (or frankly at any level because this affects blocks and AUs too) is for comparison across runtime instances potentially from disparate LMSs.

This is why @bscSCORM quite rightly keeps bringing up hashing in these identifier discussions, unfortunately it may not be practical. But perhaps it is time to re-think that as a negative, then people might have to know what they are doing when they create them.

**Comment by bscSCORM** [comment]
**Hashing:**
I don't think I've brought up the hashing idea with this group, so what it is would be that the ID for a course structure, or an activity (AU), MUST be set to the hash (we'd require a specific algorithm)  of the definition for that course structure, or activity, in some specific serialization (and excluding the ID because obviously we can't know what the ID is to hash it before we calculate the hash). Of course we'd have to also spec some additional component to the URI to pad out the hash and make it a valid absolute URI.

The rationale being, people are bad at coining and managing identifiers. The major downside would be that there would no longer be a way to make a trivial change (eg: spelling) in a course definition and have the course automatically be recognized as the same, but the major upside would be any systems seeing the same ID could be confident every instance of that ID represents the same course structure or activity (AU) definition.

**Passing Score:**
I think an exception for passing score makes sense. (even in the hashing scenario, we could avoid hashing it). My main concern is that we have to draw a line somewhere, the line has to be clear, and we should spec that statements are written which contain any information that we allow to vary from what's in the course structure.

**Comment by cawerkenthin** [comment]
@brianjmiller I don't see how @davidpesce example is "runtime".  The course isn't running at the time the LMS Administrator decides to modify the passing score.

@bscSCORM I am concerned that, as in your example, something as trivial as modifying the description of a course results in something considered "new".  While I like the idea that credit for a course could apply across organizations, I am not sure that was identified as a cmi5 goal and perhaps is solving a problem that is out of scope?  In the event that an LMS wanted to implement "global credit", they could simply not provide a feature for editing a course once it is imported.

**Comment by brianjmiller** [comment]
@cawerkenthin as I said above, it is runtime only until that course is "exported" or someone needs to view it outside the LMS, etc. If an LMS wants to "cache" a local change that will get passed to the AU at runtime I still consider that a runtime change. From an implementation perspective the key difference there is that the LMS would need to maintain the original course structure for export purposes.

**Comment by bscSCORM** [comment]
@cawerkenthin cmi5 builds on xAPI, and xAPI activity IDs are intended to be meaningful globally (hence the language about "unique" we brought in). If we want to call out "global credit" as a non-goal for cmi5, we should probably ensure that different LMSs do not use the same xAPI activity IDs, ever. In which case we could spec the cmi5 IDs as being something that could be appended to a URI the LMS would provide, rather than being a complete URI. Or we could completely remove the concept of identifier from the course structure.

Back to talking about the case where we do try to have identifiers with global meaning, I don't mind exporting a course structure with the same ID but different "defaultMasteryScore" or "defaultSomethingElse", but I come back to the line I want to draw -- if we want identifiers to have global meaning, then values in the course structure should either be suggestions that may be ignored / re-written at runtime ("defaultMasteryScore"), or values that we forbid meaningfully modifying without changing the  id (title?). We do run into the issue there of determining what a "meaningful" change is. A proxy I like to use for that determination is "if a system ignores your edit, and that matters, the change was meaningful", which leads me back to my suggestion:

> An LMS, or any system that has a copy of a course structure, MAY ignore any other definitions of that structure with the same ID it sees, and assume that the copy it already has is correct.

Because we'll have defined properties as either "just a suggestion" (defaultMasteryScore), or "no meaningful changes allowed" (title), so either way, it's not a big deal (possibly annoying, but not a big deal) if a system uses an old definition.

**Comment by davidpesce** [comment]
@brianjmiller ahhh, now i understand...

> 
Except that use case is still runtime and has nothing to do with the supposed "edit" feature, where presumably "edit" is intended to tie together with "export". So if one LMS administrator wants to say everyone passes all the time then that is fine at runtime
> 

I thought the edit/export feature had faded from this discussion. I don't think the LMS should be able to overwrite the content's masteryscore (without changing the ID). 

For example, when a 'certified' course (think Cisco, Microsoft, etc) has a required masteryscore and includes credentials based on that passing score. The LMS should be REQUIRED to change the ID if it edits the content's masteryscore and exports it. This could be a way to verify that a user actually passed the 'certified' course (because it would have the original ID).

That being said, it'd be easy enough to copy over the ID from the original course and import into the LMS.

**Comment by cawerkenthin** [comment]
So the original developer of the course, who may know utterly nothing about the business that buys the course, "owns" the masteryScore.  The LMS Administrator, who knows everything about the business, must bow to the course developer.

We absolutely will not comply with that.

**Comment by bscSCORM** [comment]
This is a great discussion, I think we need to keep in mind all our
disagreement seems to be in the area of "what constitutes a different
course". Of course LMSs may need to adjust the mastery score, the
disagreement is around whether that means they have created a new course
structure.

**Comment by davidpesce** [comment]
Owns the original masteryscore. If it's not a 'certified' course (I'm hoping someone who would create and credential passers, would know about the business of who should/should not pass). 

All it's saying is that if you edit the masteryscore, it's not the same as the original. In most instances it won't matter that it's not the original version and the business that buys the course essentially owns the 'new' version.

Say the FDA decides to put out courses on the 510k process. All passers should have passed it with the FDAs masteryscore. But if a particular company wants to ignore that, they can. The only caveat is that, the passing score isn't valid outside of that particular business that modified the course.

**Comment by bscSCORM** [comment]
Something else to note here, even if we mandate changing the cmi5 ID for certain edits, nothing prevents an LMS from grouping packages with different cmi5 IDs together and considering them to be one package, within the LMS reporting. Of course the raw xAPI statements will contain different IDs.

That leads me to thinking about how we could potentially satisfy both the "strong identifier" use case which would lead us to be strict about requiring new IDs, and the "LMS knows best" use case which implies those requirements should be relaxed.

How about defining a secondary property "originalID" for both the course structure and each AU, that could be used by any system making edits which wanted to maintain the association with the original source being edited? We'd then be very strict about any change requiring a new ID, but if whoever made the change thought what they had was still "basically the same thing" they could tag the originalID, and AUs would be required to report the originalID as a context activity (allowing queries to find statements based on that original ID).

This would allow reporting systems to chose which question they want to ask:
* Let me see results for (someId)
* Let me see results for course structures which someone has asserted are effectively similar to (someId)

This is getting a little more complicated, but I'm not sure there is a better answer, given the reasonable case to be made for both use cases.

**Comment by cawerkenthin** [comment]
@davidpesce The masteryScore used during a session is written in both the State and the passed/failed Statement, so it would be observable that the score was not the original.

@bscSCORM I like your approach.

**Comment by brianjmiller** [comment]
@bscSCORM and I discussed this a bit further after last week's call. Based on that I'll try to outline some specifics around his proposal (which he has not vetted):

* Switch the current AU "id" to be an optional value named "publisherId" or "globalId" (or similar), this identifier would be provided to the AU via the `contextTemplate` in the LMS launch data when it is present in the course structure file. By putting it in the `contextTemplate` the AU would have to provide it in all "cmi5 defined" and "cmi5 allowed" statements (based on other requirements).
* The LMS would now serialize (this mechanism would need to be heavily specified) the Activity Definition of the Activity that will be placed in the `object` of the statements and hash (specified algorithm, encoding, etc.) the serialization to be combined with a specified prefix that would become the "id" of the Activity. The per AU launch LMS determined values of `masteryScore` and `moveOn` would need to be placed in the `extensions` of the Definition to be serialized along with values such as `type`, `name`, etc.

This leaves open the following questions (and probably others):

* Should the Activity Definition be provided in the LMS launch data so that the AU receives it? If this is the case then no need to provide `masteryScore` and `moveOn` separately. Does the LMS have to provide the full Activity Definition in the "Launched" statement? Any others?
* If we move to inclusion of the Activity Definition in the launch data, is there a reason to not just make it the full Activity object (including "id") and remove that parameter from the launch query parameters?
* The hashing concept is only defined at the AU level by the above, but there is still the problem of making other alterations to the course structure (including but not limited to the inclusion of, subtraction of, or re-ordering of AUs or blocks or otherwise altering metadata such as title or description). Presumably the same serialization and hashing mechanism could be applied to `object` identification for Satisfied statements.

**Comment by brianjmiller** [comment]
I only mentioned the course and blocks, the above would presumably apply to objectives too.

**Comment by MrBillMcDonald** [comment]
Tabling until consensus

**Comment by cphill02** [comment]
I've seen developers change course id's and nothing else to specifically break the reporting and start new and I've seen LMS administrators re-purpose the same course id even though content and structure significantly changed to keep reporting of the course in the same data set for years.

If the content id is being reused or changed it is down to impact the LMS reporting. Please let LMS Administrators and Content Developers continue to control when and if they need to change ids.

**Comment by andyjohnson** [comment]
I think as a philosophical discussion, this is really interesting and invites creativity in problem solving.  Practically, I don't see how doing any sort of checking/replicating on a course structure does anything.  Let's look at two scenarios:

Scenario 1:  We only care about performance of this course in this LMS.  In this case, letting administrators change the course structure is on them.  If we don't care about comparing the same course/activities outside of our organization, then let them edit away.  Any sort of course id/replication/etc. is only to protect the admins from themselves, which I don't feel is worth it.  Chances are, they'll still find a way to mess up and we've made it harder for them just to edit fix it.  I do think having a clear RECORD of what the values were when a particular learner took the course is important as there should always be a Statement trail that explains why I fail with a score of 99 and Art passes with a score of 20.

Scenario 2:  We care about how this course does across systems or even organizations.  If this is the scenario, then we're going to have to trust the course ID and those involved in deploying it.  Why?  Because controlling it otherwise is impossible.  First, any sort of hashing or replicating means that a change to the course structure makes it a new course or at least a new id, whichever way you slice it.  The biggest problem I see here is that the AU urls are going to change.  If they don't change, we're in a magical place where all content is online in one place and it is perfectly maintained and always available and not distributed or brought into a "local" instance.  Not practical.  If the urls are allowed to change, then you already have the problem of having no way to validate that what is on one end of a URL is the same as the other, not to mention you never have the same course ids.  What good are two identical course structures if the content could have changed?  We are still left with determining if two courses are "similar" enough.  I say the best way for interoperability is to make creating course structures simple and have the state data populated at run-time and not have the LMS do anything special based on what has happened historically with the course structure.  Because that way, people won't feel the need to coin all of their own IDs and create proprietary structures and we may actually see reuse.

That's my 2 cents, see you on the call tomorrow!

**Comment by cawerkenthin** [comment]
To know one's surprise, I'm sure, I agree with @andyjohnson.

**Comment by MrBillMcDonald** [comment]
Per the March 18th meeting, we agreed to do the following to resolve the "Activity ID Issue" (Which is what this issue is really about):

1.	Activity ID for launch line (comes from the LMS – LMS generates it)  -- LMS MUST NOT use the “Publisher ID” (AU ID the from the course structure).
2.	LMS writes Publisher ID to the state
3.	AU Reads Publisher ID from the state
4.	AU writes the ‘Publisher ID Context in its statements 

The rationale being that the LMS will manage the Activity ID generation, but the ID from the course structure will also be added to statements as a "reference".

**Comment by brianjmiller** [comment]
The merged PR addresses the discussion that happened as a result around identifiers, but the core of this issue is still a problem and needs to be addressed. That issue being that the specification indicates that the values provided in the state come from the course structure, but no where does it indicate that the LMS may change those values (except as producing a new course) between import of the course structure and the launch of the AU for that registration.

**Comment by brianjmiller** [comment]
See #424 for new issue.
