### ISSUE TITLE
Meaning of progress when it differs between statements

### ISSUE THREAD

**Issue by garemoko** [AICC/CMI-5_Spec_Current#389]
I'd like to check my understanding of the meaning of the progress extension. 

I have a batch of cmi5 statements kindly provided by @brianjmiller. In that batch and for a single session, I have a 'passed' statement containing the progress extension with a value of 80 and a 'completed' statement where the value is 100. 

From those statements and looking at the cmi5 spec I'm making the following assumptions. Please let me know if these are right or not!

* Progress can be sent with any statement, and can be sent multiple times within a session. 
* Regardless of the statement progress is sent with, it always has the same meaning: progress towards completion (Rather than something similar to duration where the type of duration changes based on the verb).
* Progress can go both up and down, therefore reports representing cmi5 data might might it helpful to display both max and final progress for a session.

**Comment by brianjmiller** [comment]
I agree that the language around progress probably needs to be beefed up to be interoperable meaningfully. I don't think your first two bullets are assumptions. I *guess* the Result lead in section could be more clear, but since 'progress' is listed under result and it talks about what you can do with statements that are cmi5 defined and not, I consider it pretty clear that it can be included in all of them that have a Result. As for the meaning `An integer value indicating the completion of the AU as a percentage.` seems pretty clear. What "completion" is itself is difficult to say and is going to be AU specific.

The last question is certainly a good one, can progress towards completion go down? I'm fine with it but it is certainly an interesting question. Given the small set of statements that an AU can send it may make more sense for AUs to use cmi5 allowed statements for capturing progress, at least in fine grained scenarios. If we think that is going to be a common use case then it might make more sense to use a "progress capture" statement instead.

**Comment by MrBillMcDonald** [comment]
Per March 11 Meeting will refine progress description as follows:

9.5.5 Extensions
9.5.5.1 progress

AU Obligation:	Optional.  AU SHOULD NOT set a progress value if in a Completed statement or if it has previously issued a Completed statement for the AU in the current registration.



9.3.3 Completed

ADD the following to description:

The use of the Completed verb indicates progress 100%.

**Comment by garemoko** [comment]
I think it'd be better to require the progress extension (at 100%) with the completed statement. That way a Learning Record Consumer knows it can just look at the progress extension to get progress rather than having to look at both progress and verb.

**Comment by MrBillMcDonald** [comment]
The group found that requiring a progress extension of 100% to be redundant (and also another opportunity for error) so we deliberately did not include it as a requirement.
