### ISSUE TITLE
Determination of "Satisfied" wording change caused by "Waived"

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#393]
Under the "moveOn" requirements (https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#moveon) the language specifically calls out verbs that trigger whether or not the "moveOn" criteria are met, then under "Satisfied" it indicates that the LMS determines based on the "moveOn" criteria.

Does "Waived" automatically trigger satisfaction? Should the language under the "moveOn" requirements really be based on the Result object's components of `success` and `completion` (which are included in "Waived" statements) or do we add "Waived" to the list triggering it?

**Comment by MrBillMcDonald** [comment]
Per Feb 26 meeting:

**Does "Waived" automatically trigger satisfaction?**

The process of waiving something is the same as meeting "MoveOn" Criteria.  In that a "satisfied" statement would be issued and rollup rules would be executed.
  
(See issue #392 -- Waived uses session language what does that look like? )

**Should the language under the "moveOn" requirements really be based on the Result object's components of success and completion (which are included in "Waived" statements) or do we add "Waived" to the list triggering it?*

No. Because MoveOn is a criteria while you are talking an AU.
