### ISSUE TITLE
Should contextTemplate use "session" (as specified in the spec) or "sessionid" (as shown in some examples)?

### ISSUE THREAD

**Issue by sfraysse** [AICC/CMI-5_Spec_Current#530]
Hi,

I am not sure to understand how the session ID should be specified in the "contextTemplate" of the "LMS.LaunchData".

The spec says that the extension "https://w3id.org/xapi/cmi5/results/extensions/session" should be used.

However, some examples on http://aicc.github.io/CMI-5_Spec_Current/ use the "https://w3id.org/xapi/cmi5/context/extensions/sessionid" extension.

For instance this example: http://aicc.github.io/CMI-5_Spec_Current/samples/scenarios/03-completed_or_passed-passed/

Could you please clarify this point?

**Comment by brianjmiller** [comment]
This is a conflict in the spec, if you reference the section on extensions here:

https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#9631-session-id

You'll see the identifier from the examples. I'd consider the spot you referenced in the `contextTemplate` (https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#100-xapi-state-data-model) to be descriptive rather than normative language and I think is errata. Having said that, it is most certainly a contradiction and I suspect we'll have to wait until the next call (which I believe is this coming Friday) for a decisive answer.

FWIW, I think we should keep the one in 9.6.3.1 and "fix" the other spot to match it or not include it at all and reference the mentioned section as we do with the publisher id in that same spot.

**Comment by cawerkenthin** [comment]
@brianjmiller @sfraysse Agree with Brian, Section 10 should be corrected as well as the cmi5 vocabulary.

**Comment by MrBillMcDonald** [comment]
Will update section 10 per Nov 18th meeting to correct the example.

**Comment by sfraysse** [comment]
Thanks all for this clarification!
