### ISSUE TITLE
Is there a list of vendors/products/tools tracking their CMI5 support?

### ISSUE THREAD

**Issue by kveretennicov** [AICC/CMI-5_Spec_Current#536]
I am trying to figure out if there are any tools already available, or implementation plans announced, to author and deliver learning content with CMI5. A document tracking industry adoption would be of great help.

Thank you.

**Comment by nphoenix** [comment]
I believe Art Werkenthin with RISC has done something with FLOAT related to PDF annotation.

Henry Ryng

**Comment by MrBillMcDonald** [comment]
Konstantin,

You are quite right!  We need to have an "cmi5 adopters" page on our site !

To my knowledge, there at least 3 vendors who have currently implemented cmi5 in their products.  They are as follows:

1. RISC, Inc (LMS)
2. iSpring Suite (Authoring Tool)
3. Rustici SCORM Cloud, SCORM Driver, SCORM Engine (LRS and Middleware)

There may be more, but they haven't told us yet !  

Because of Rustici's support we do expect a lot more LMS and Tool vendors to announcing cmi5 support.

FYI - RISC and iSpring together announced the first end-to-end cmi5 solution in November:
http://www.ispringsolutions.com/company/press-releases/first-cmi5-compliant-solution.html

**Comment by MrBillMcDonald** [comment]
Konstantin,

We updated our site to include a list of cmi5 adopters as follows:

http://aicc.github.io/CMI-5_Spec_Current/adoption/
