### ISSUE TITLE
questions to fully understand cmi5 quartz spec

### ISSUE THREAD

**Issue by knowledgeplaces** [AICC/CMI-5_Spec_Current#542]
Hi,

The cmi5 AU launch URL contains an actor parameter which is an Actor of object type Account.

So the AU can get this Account which should typically contains the name of the user in the LMS, and could then use this name to customize the display of the AU content, such as a "Welcome [account]" text to be displayed on the welcome page of the AU.

According to XAPI spec, an Actor MUST NOT include more than one IFI (Inverse Functional Identifier).

So, as the Account is already an IFI, if I understand well, the actor parameter in the launch URL cannot also deliver the mailbox, because the mailbox is also an IFI.

I would be nice to also have access to the user mailbox, so the AU could use it for different purposes, such as, of course, sending email to the user mailbox.

Please advise on how this could be currently implemented. 

If not,then maybe the XAPI spec should be updated to support more than one IFI for an Actor.

**Comment by MrBillMcDonald** [comment]
#1 - With cmi5 the LMS could use EITHER the mbox or account for the actor.  The spec example uses account but that is not a requirement.

#2 - In cmi5, LMS is not required to provide the Learner's email address.  You could request the email from the learner's agent profile (if the LMS has it, is willing to provide it, and can provide it in a manner that the AU understands - there is no standard for passing the email to the AU )

#3 - xAPI community originally allowed for both (mbox and account) and later changed the xAPI spec  in order to address PII (Personally Identifiable Information) concerns.  It is unlikely that they would change it back.
