### ISSUE TITLE
how to report a score not related to passed or failed

### ISSUE THREAD

**Issue by knowledgeplaces** [AICC/CMI-5_Spec_Current#544]
There are several situations where you need to report a score, but there is no notion of passed or failed associated with it. Think for instance about the TOEFL, https://www.ets.org/fr/toefl/.
You don't pass or fail the TOEFL, you just get a score.
Each organisation will set a "required" score or will just use your score to have an indication of how good is your english.
So, it seems obvious to me we should be able to report scores in cmi5.
From the spec, https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#score, score can be reported only in Passed or Failed Statements.
I would suggest to add the ability to report score in the Terminated Statement.
I would also suggest to have the ability to report scores by category.
Any feedback welcome, especially if I am wrong in understanding the spec.

**Comment by brianjmiller** [comment]
I would suggest this falls into the category of a "cmi5 allowed" statement. Essentially any statement not including the `https://w3id.org/xapi/cmi5/context/categories/cmi5` context category Activity. This just removes the restrictions as relates to `masteryScore`, etc. but it seems outside of a passed/failed context that attribute shouldn't apply anyways. Terminated is reserved for indicating the end of a session, and since a session itself isn't necessarily scored the property doesn't make sense there. The score (even when not passed/failed) may occur before the end of the session, etc. Recording scores by category can also occur within "cmi5 allowed" statements, they just won't be interpreted by the LMS as it doesn't understand a 'category'.

**Comment by knowledgeplaces** [comment]
@brianjmiller  "but it seems outside of a passed/failed context that attribute shouldn't apply anyways". Not agree, see my TOEFL example, a score does not need to be associated with passed or failed, it can be just used as a level.
@brianjmiller "a session itself isn't necessarily scored". I agree, but it may be. See my TOEFL example, or see any lauch of SCORM content which can send a score even without passed or failed.
Reporting scores to a LMS is essential, and as the goal of cmi5 is to standardize interactions of XAPI content with LMSs, I am not comfortable with sending scores using "allowed statements".  I would like a defined cmi5 statement.
My company develops a LCMS where each training can contain multiple quiz. You can get a score on each quiz, and you get a global score on the training, which is computed using rules defined by the author in the LCMS.
I am comfortable with sending individual quiz results using cmi5 allowed statement, and this is what I do.
But I would expect a cmi5 defined statement for global score.
For instance, there is an extension available to set a "progress" in the Terminated statement. Why not allow an extension for "score"?
Really feel there is something missing for reporting session score not associated to passed or failed.

**Comment by brianjmiller** [comment]
I was referring to `masteryScore` as not applying when not doing pass/fail.

Also note that the `masteryScore` could be specified as 0 (or not at all), in which case you'd always get pass and could still record a score. If the LMS wants to ignore a pass as a "pass" when the `masteryScore` is 0 then that seems like it would make sense. But it is still a "passed" statement from an xAPI perspective so you can include a score. In the case you describe, it is either "passed" (cause any score is acceptable) or it is undefined (no statement present === not attempted).

What a "passed" statement means for a given package + LMS combination is still outside of the scope of cmi5 spec. cmi5 doesn't really make a claim whether "passed" was determined explicitly or implicitly (saying any score is passing), only that it has been recorded.

**Comment by knowledgeplaces** [comment]
I was also thinking of using a Passed Statement with an undefined masteryScore as a workaround.
But then, I don't have the ability to display a "neutral" indicator in the LMS, for a session recorded with a score. It will always be marked as passed or failed, based on cmi5 defined statement saved for that session.
Also it is not a big deal, I think the cmi5 should give us the ability to record "neutral" scores, to differentiate them from passed or failed scores. 
As there is an extension "progress" on Terminate statement when there is no "Completed" statement, I think a "score" extension on Terminate when there is no "Passed" or "Failed" statement would make sense, and would give a non ambigous information to the LMS.

**Comment by brianjmiller** [comment]
FWIW, I think I may have even advocated a "score recorded" statement to avoid this hassle as well as some others we faced with including it in passed/failed. I can say this has been gone over fairly exhaustively and I don't know that I consider "LMS X doesn't understand an implicit pass" as a good reason to a) make a spec change, b) include a score in something like "terminated" which has a very explicit purpose for existing. LMS X will need to consider how to summarize cmi5 particularly in the multi AU case because there aren't really "rollup rules" to speak of (outside of `moveOn`), so this is one of those cases that will have to be considered. I could see adding a "record score" type of statement, but would be back to questioning why that is not just an implicit pass, and spec churn will hurt adoption.

Also FWIW,

https://github.com/AICC/CMI-5_Spec_Current/issues/263
https://github.com/AICC/CMI-5_Spec_Current/issues/390
https://github.com/AICC/CMI-5_Spec_Current/issues/449

**Comment by knowledgeplaces** [comment]
I will go with a Passed Statement. Not perfect, but can't wait for cmi5 enhancement.
Thanks for feedback.
