### ISSUE TITLE
Launch an AU from another AU

### ISSUE THREAD

**Issue by knowledgeplaces** [AICC/CMI-5_Spec_Current#547]
I know this is probably not supported by the cmi5 spec, but I have a real world case and would like to have feedback on how to do it.
I have a customer who publishes on our LMS individual AUs built with Adobe Captivate, and other AUs built with our CMS.
He would like to be able to embed a Captivate AU in different CMS AUs, and still get the tracking through XAPI.
I know how to embed the Captivate AU into a CMS AU so it is displayed, I can use an iframe for that. But how can I tell the Captivate AU to track its data back to the LRS through cmi5?
Even if I use the AU launch URL, it is within the same LMS session, so I can't reuse the AU launch URL, the fetch URL has already been used by the main content.
Please advise.

**Comment by brianjmiller** [comment]
Basically, as you point out because of the session mechanics, you can't. What does the AU nesting provide that say course structure block support with separate launches doesn't?

**Comment by knowledgeplaces** [comment]
From a UX point of view, the goal is to have the Captivate AU displayed in an iframe in a page of a CMS AU.
I understand that if I use the cmi5 Course structure, the user will launch the Captivate AU and the CMS AU separately, which is not the UX my customer is looking for.
Please correct if I am wrong.

**Comment by brianjmiller** [comment]
You are correct. I understand the technical goal, but what is driving that as the technical goal? What does nesting the AU inside another AU achieve otherwise?

**Comment by knowledgeplaces** [comment]
First, the UX. The Captivate AU is a software simulation, and the CMS AU is a concept oriented course, presenting the concepts used in the software. But it is more convenient to present them to the user as a single AU. The user discovers some concepts, then experiments with the software simulation, and then there is a conclusion. Captivate is fine for building the simulation, but not the concepts, where our CMS is very good.
Second, reusability. The same Captivate AU may be reused in multiple AUs built with our CMS.
But I have an idea.
We develop both the CMS and the LMS which hosts the CMS AUs and the Captivate AUs.
Our CMS is WordPress based so we can easily customize it.
For instance, we could have a shortcode [embedAU id=123], where id is the id of the Captivate AU in the LMS.
The shortcode processing would be as follow:

- Query the LMS to get cmi5 launch parameters in "child mode", with a "child session" Id
- Redirect to a page whose URL is the cmi5 launch URL on the Captivate AU, using the cmi5 launch parameters sent back by the LMS
- the Captivate AU can then use the fetch URL since it is for another session Id
- the Captivate AU can get the LMS.LaunchData for this child session Id
- In this LMS.LaunchData, the LMS would have set a returnURL on the page of the CMS where the shortcode is embedded
- So the user experiences the Captivate AU, and when it quits, it goes back to the CMS AU.

From a statement point of view, we would have:

- user launches CMS AU
- user initializes CMS AU
- various statements of the user on the CMS AU
- user launches Captivate AU
- user initializes Captivate AU
- various statements of the user on the Captivate AU
- user terminated Captivate AU
- various statements of the user on the CMS AU
- user terminated CMS AU

What do you think? Is it "cmi5 compatible" or "cmi5 friendly"?
Maybe we could add some context to the statements of the Captivate AU, to formalize the child relationship with the CMS AU.

**Comment by brianjmiller** [comment]
Ultimately it is compatible, I dare say even friendly. I wouldn't say it is "interoperable" but then, most likely you don't care (and we don't have to either).

Because you control the CMS AU and assuming the CMS and "LMS" are tightly coupled then the CMS AU can be launched using standard cmi5 practices, then the CMS AU would need a way to communicate with the LMS to get a separate and distinct cmi5 launch URL to load the Captivate AU into an iframe for instance. The way in which the CMS AU gets that launch string would really be outside of the scope of cmi5 and is why I say it isn't "interoperable", meaning you couldn't take that CMS AU and package it up and run it any other cmi5 launching system that doesn't provide that same support, but that isn't a deal breaker.

There are some stipulations that make this potentially less workable (from the reporting side), for instance:

* They couldn't share the same session because the separate launch scenarios would trigger a new session to be started,
* Probably more problematic is that they couldn't even share the same registration based on the language around how abandonment is drafted which prevents simultaneous sessions for a given registration, 

> In the absence of a "Terminated" statement, the LMS MUST make the determination if an AU abnormally terminated a session by monitoring new statement or state API requests made for the same learner/course registration for a different AU. The LMS MUST record an "Abandoned" statement on behalf of the AU indicating an abnormal session termination. After recording an "Abandoned" statement, the LMS MUST NOT allow any additional statements to be recorded for that session.

You could do some things to mitigate this problem, for instance the thing that the CMS does to get the sub-AUs query string could instruct the LMS to include data (even an Activity) in the context template object that is put in the state for the sub-AU to fetch during launch time that would allow you to later tie all statements from the outer AU's session together (via `related_activities` for instance).

**Comment by knowledgeplaces** [comment]
Thanks Brian for detailed feedback. I can go ahead with that.
