### ISSUE TITLE
Cmi5 sequencing

### ISSUE THREAD

**Issue by Getafix-hub** [AICC/CMI-5_Spec_Current#595]
I am wondering is there are any plans to add sequencing capabilities to Cmi5. 
Here is an overview of the requirements of interest:

1. The sequencing engine is modeled as a Finite State Machine with a Stack where:
   - state represents the AU
   - transition represents evaluation criteria based on AU completion Key Performance Indicators harvested from the LRS. For example, the score of the completed AU.
   - the actions are push and pop operations (of the next AU) on the stack. 

2. Upon completion of an AU, the sequencing engine is invoked to generate the next AU to be executed (or null if the course is complete).   

3. A simple sequencing engine behavior is described by this pseudo code: 
<pre>
GenerateNextAU(AU, agent)
{  
     [score, data1, data2,  dataN] = getResults(AU, agent) // KPIs

     if   score < 0.1: Stack.push(AU_1)   // set next AU to AU_1
     elif score < 0.2: Stack.push(AU_2)
     // etc...
     elif score > 0.9: Stack.push(AU_n)

     if Stack.isEmpty(): return null     // this is the end of the course 
     return Stack.pop()                  // return the next AU 
}      
</pre>
4. The AU are sequencing-unaware, and pass/fail unaware

5. The sequencing definition is packaged independently of the AUs

6. The Stack FSM allows organizing instructional content in a multi-dimensional space by defining knowledge topologies.
For example, if a Course C requires courses A and B and if the learner has mastered A and B, the C course will be  composed of the following AUs:
TA, TB, C1,  C2, C3, where TA and TA are tests for courses A and B.  
If the learner fails B test, the C course learning sequence would have looked like:
TA, TB, B1, B2, B3, C1, C2, C3

**Comment by MrBillMcDonald** [comment]
Christophe,

At this time there are no plans to add such capabilities.  In general, sequencing is usually specific to LMS implementation and difficult to get industry consensus on.

Complex sequencing was very deliberately not included in the cmi5 specification based on the experience of AICC and SCORM sequencing efforts in the past.   LMS vendors were reluctant to adopt them because of the cost and the lack of agreement about their usage.

cmi5 course structure does have a hierarchy and simple metadata for objectives and completion rules.  

At some point additional simple rules (such as prerequisites) might be considered.   

Sincerely,

Bill McDonald
