### ISSUE TITLE
Add option to use Bearer scheme instead of Basic for authentication

### ISSUE THREAD

**Issue by ssimo3lsuhsc** [AICC/CMI-5_Spec_Current#609]
Hello!
I've been struggling to create an LMS that will gracefully handle users that represent real people (with ordinary sign-in accounts representing e-mail addresses that have been confirmed) with users that represent AU sessions. I have de-Base64'd the example Basic Auth token, and it in fact decodes to "Aladdin:Open Sesame." In reality, however, this will result in an explosion in headaches for developers because it forces them to distinguish between users with e-mail addresses and false users without. I have been trying for weeks to reverse-engineer Microsoft ASP.NET Identity because there is no way I could require confirmed e-mail accounts only from users with the role "real_user."

That's why I want to at least _try_ to suggest to add an optional launch paramter `use_bearer`. When the launch URL includes `use_bearer=true`, the AU would know to use `Bearer` instead of `Basic` in the Authorization header.  There` appears to be a misconception about Bearer tokens in that they are never revocable. In fact, there was a proposal, [RFC 7009](https://tools.ietf.org/html/rfc7009), made in 2013(!) , that indicates that it is indeed possible to implement Bearer tokens while playing nice with the requirement that launch URLs are one-time-only and that the "Terminated" action should invalidate the token. Trust me when I say that although JWT is not a revocable Bearer token implementation, there are other implementations that are. If you want me to give you some examples, I'd be glad to.

**Comment by MrBillMcDonald** [comment]
Thanks for your input.  

We did discuss this issue in our Aug 28th cmi5 meeting.  This is a complex topic and will require further discussion,  We will discuss options for authentication in our next series of meetings.  

Please feel free to join our web conference - 
https://github.com/AICC/CMI-5_Spec_Current/wiki/Weekly-cmi5-Working-Group-Meeting---Conferencing-Instructions

Bill McDonald

**Comment by MrBillMcDonald** [comment]
This is not a trivial issue as it affects core interoperability.   

We have extensively discussed this issue over the last two meetings.  We will consider other authorization headers (like bearer) in future releases of the cmi5 specification.   At this time we do not have a schedule for the next release of cmi5. 

Can you explain what the advantage of using bearer token over basic auth in this scenario?   (as this is an authorization scheme not an not an authentication scheme).

If you feel that you need to move this issue forward with our group, please attend our web conference:

https://github.com/AICC/CMI-5_Spec_Current/wiki/Weekly-cmi5-Working-Group-Meeting---Conferencing-Instructions

**Comment by ssimo3lsuhsc** [comment]
This will not affect existing CMSes at all. They already have their token generation and authentication schemes in place. I should probably have said that most people think of JWT when they think of the Bearer authorization scheme. In fact, I was thinking of an entirely different authentication scheme that is nonetheless always backed by the Bearer authorization scheme. If you ever get the chance, you should Google the exact phrases “opaque token” and “reference token.” There is no widely-adopted standard for Bearer tokens that can be marked as disposed, but the terms “opaque token” and “reference token” are used by different software solutions that have implemented the concept. I am coding in ASP.NET Core and was hoping to use IdentityServer reference tokens as the authentication scheme of my API.

If there is any advantage to using Bearer auth, it is that it is already supported by a widely-used library in almost every programming language. Microsoft has discontinued its built-in support for Basic auth in ASP.NET Core Identity, so in order to implement it, I have to reinvent the wheel. It is very frustrating for me because I believe I will need to do it on several projects.

Stuart Simon
Graphics Specialist
Human Development Center
LSU Health New Orleans
411 South Prieur Street
New Orleans, LA  70112
504-556-7567
ssimo3@lsuhsc.edu<mailto:ssimo3@lsuhsc.edu>

**Comment by MrBillMcDonald** [comment]
Stuart,

ASP.NET Core Identity is an API that supports user interface (UI) login functionality. 
It manages users, passwords, profile data, roles, claims, tokens, email confirmation, and more. 
It doesn't really fit the cmi5 launching system which is for  "authorization" (not authentication).

We have members of our group who have implemented a cmi5 compliant LMS using ASP.NET so we really don't see an issue here.  

This issue is not widespread and providing for alternative authorization header schemes does not enhance security or appear to provide any other substantive advantages for cmi5.  Should the situation change, the group will re-assess alternative authorization header schemes for future spec versions.

Please feel to join our weekly web conference if you wish to discuss issue further:


-  [https://github.com/AICC/CMI-5_Spec_Current/wiki/Weekly-cmi5-Working-Group-Meeting---Conferencing-Instructions](https://github.com/AICC/CMI-5_Spec_Current/wiki/Weekly-cmi5-Working-Group-Meeting---Conferencing-Instructions)


Sincerely,

Bill McDonald

**Comment by thomasturrell** [comment]
Sorry to comment on a closed issue.  I agree with much that has been said by @ssimo3lsuhsc.

As someone that works for a vendor that hasn't implemented cmi5 I hope my perspective might be useful.

It's great that there are vendors that have implemented basic credentials in their LMS's but there are genuine reasons why some vendors might be unwilling or unable to do this (for many this is a step backwards not forwards).

I believe that the unofficial launch specification is more flexible and future proof than the launch mechanism outlined in cmi5.

The unofficial launch specification allows the system (not necessarily an LMS) to specify the entire authorisation header.

The use of basic authentication is being deprecated in many well known public API's (incidentally GitHub are removing support tomorrow). I realise this isn't a killer argument but it is noteworthy.

I'm not saying the cmi5 specification shouldn't allow vendors to use basic authentication but it seems short sighted to prevent other mechanisms. At the end of the day it makes no difference to the course, it should just use the authentication header that it has been provided.

There is much to like in the cmi5 specification however this particular issue could, in my opinion  prevent widespread adoption.

The company I work for would like to support cmi5 courses but doesn't want to be tied to any particular authentication protocol and it certainly doesn't want to implement basic credentials.

I would have liked to have seen requirements on how a course should handle an authentication header which no longer allows access to the LRS endpoint (presumably due to the credentials having expired).

I would be happy to provide more perspective on this if it would be welcome.

Kind regards.
