### ISSUE TITLE
9.5.5.2 - Does value space imply a MUST?

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#631]
> The LMS MUST set this value in statements it makes with the verb "Waived". The value SHOULD be one of the following -

The requirement reads with a SHOULD about the value above, but then a "Value Space" is provided suggesting that the value has to be one of the ones provided.

> "Tested Out"
> "Equivalent AU"
> "Equivalent Outside Activity"
> "Administrative"

Does the existence of the latter imply that the requirement is already a MUST? Or should the value space not be included given that the same list of values is already provided in the description after the SHOULD?

**Comment by MrBillMcDonald** [comment]
This issue will be revisited with more group members.

**Comment by MrBillMcDonald** [comment]
Discussed in the June 11th Meeting.  The group agreed that SHOULD indicated for the values listed was indeed intended to be optional and other values outside of the ones lists could be used.   The group also agreed to change the "value space" to "string"  (since the values are not constrained to the SHOULD list)
