### ISSUE TITLE
Development branch should be renamed main from quartz

### ISSUE THREAD

**Issue by thomasturrell** [AICC/CMI-5_Spec_Current#696]
The development branch (also the default branch) is currently named quartz which is believe is confusing because there is a tag for the Quartz release of the specification. It might be unclear to people reading the specification that the default branch is not the Quartz release and is in fact the development branch.

The alternative approach would be to have branches for each release and then a 'work in progress' development branch (which isn't the default branch). All pull requests would be merged to the development branch and the default branch would be the latest release. No pull requests would be accepted to the latest release.

I think there needs to be decision to release from a branch or tag. Tags are immutable where as branches aren't, so personally I favour releasing from a tag.

I am interested in other peoples views.

**Comment by brianjmiller** [comment]
I'm generally in favor of doing something a little more systematic. We do need to recognize that as a spec this is somewhat different than how you would generally version and handle software products. For instance all of the recent PRs have changed "quartz" from its original wording, but not its intent nor requirements, so the group generally considers the current specification to still be "quartz".

Having said that I do think it would be valuable to start focusing more on semantic versioning of the spec. Being more clear that quartz is effectively the 1.0.0 version, tag it as such, and then make future changes (once this barrage dies down which is very soon) via a development branch that ultimately becomes 1.0.1 or 1.1.0 or even 2.0.0 depending on the level of changes being made. It may make sense to set up a patch, minor, and major branch or similar so that changes can be targeted at the correct level so that they will ultimately roll up under the correct semantic version scheme.

**Comment by thomasturrell** [comment]
Thats useful information, thank you.

The key point that I was missing is that 'recent PRs have changed "quartz" from its original wording, but not its intent'.

If you agree, I will close this issue.

**Comment by MrBillMcDonald** [comment]
Reviewed in cmi5 working group (6/17/2022)

(Per the Revision History section in the spec) ..

> Versioning in the cmi5 specification is managed in the following manner:
> - Major Version – Stones (Sandstone, Quartz, etc.) – Major changes in functionality
> - Minor Version – Editions (1st edition, 2nd edition, etc.) – Minor changes in functionality.
> - Errata – Minor corrections that do not affect functionality are not versioned. (See GitHub repository for specific revision history)

Moving forward we will discuss new Github branches and release snapshots when we begin work on  version of the spec with new features or breaking changes,

**Comment by MrBillMcDonald** [comment]
Feb 16th Meeting - Will discuss branch changes when the new GitLab repo is established for the IEEE working group.
