### ISSUE TITLE
All assignable units should send a completed and a passed statement

### ISSUE THREAD

**Issue by thomasturrell** [AICC/CMI-5_Spec_Current#707]
If an AU sends both a passed and completed statement the following move on criteria are acceptable:

- Passed
- Completed
- CompletedOrPassed
- CompletedAndPassed
- NotApplicable

If an AU only sends a completed statement the following move on criteria are acceptable:

- Completed
- CompletedOrPassed
- NotApplicable

If an AU only sends a passed statement the following move on criteria are acceptable:

- Passed
- CompletedOrPassed
- NotApplicable

Therefore the only move on criteria that a course author can use without technical knowledge of the AU are:

- CompletedOrPassed
- NotApplicable

I believe that course authors should be able to assemble assignable units into a course without having any technical knowledge of the AU. Therefore all AU's should send a completed and a passed statement. The Passed and Completed move on states would become redundant.

If all AU's  sent completed and passed statements the course author would not need to know anything about the AU when setting the move on criteria. Currently course authors could easily create courses which would be impossible for a learner to satisfy.

I am interested in other peoples thoughts and experiences.

**Comment by brianjmiller** [comment]
I think the starting premise above is an issue, why is it that a course author doesn't need to know how an AU will behave? I do agree that you end up at the conclusion given the starting premise.

But the AU should be sending statements based on what the experience itself is portraying and there could certainly be any number of AUs that send only one of passed or completed. If you start from the definition of "passed" being a "judged activity" (as the spec reads) what does it mean to "pass" for instance just reading through a PDF, or watching a video. What is being judged in that type of experience? Is determining a percentage of watching or a time spent on a page a sufficient "judging of an activity" to warrant sending passed?

I guess the other option is if the course designer knows so little about an AU then it does seem natural to then use `CompletedOrPassed` because they are effectively saying they don't care to be more specific.

**Comment by thomasturrell** [comment]
I am imagining a system where the role of course author and UA author are separate. In this system anyone can upload assignable units (created in any authoring tool) and then anyone can assemble them into courses.  In this imagined system, on upload the UA author would have to specify if the AU sent a passed statement, completed statement or both. The system would then prevent course authors from specifying move on criteria that the AU did not support. However this means that the AU author has to know what statements the AU sends. There is a lot of room for human error in the above system, I am left to conclude that the only safe move on criteria for this sort of system is CompletedOrPassed or NotApplicable.

My assumption (based on my experience) is that most AU authors will not know what statements their AU's send.

I would like to treat AU's as bricks that can be used to build courses (and blocks), however since the properties of these bricks aren't advertised it is difficult to use them. 

I think I understand your point about PDF's or videos. However I think the same questions apply to completed, what does it mean to complete a PDF or a video? My understanding is that the spec expects the meaning decided by the AU author, I think that the AU author should be required to also decided what it means to pass a PDF or a video and if they can't think of a good definition then they should use the same definition as completed (or vice versa). I think it can be judged that you have watched enough of a video to pass it, in fact I think that this makes more sense than complete.

**Comment by thomasturrell** [comment]
To be clear, I believe that this issue (if there is an issue) should be resolved in the next major release.

**Comment by brianjmiller** [comment]
>  In this imagined system, on upload the UA [sic] author would have to specify if the AU sent a passed statement, completed statement or both.

Is this a typo? Would the AU author not know if the AU sent a passed/completed statement?

It seems like no, based on

> However this means that the AU author has to know what statements the AU sends. ... My assumption (based on my experience) is that most AU authors will not know what statements their AU's send.

I think this is a bit of a stretch, and frankly if the AU author doesn't know something as simple as whether it will set pass/fail or completion then I'm not sure they should be authoring AUs. If nothing else, they should be testing (once Catapult is released) their output and it will tell them what it is doing. For any less technical AU authors, presumably they are using an authoring tool or some other library, system, off the shelf product that they should just ask the creators of what it is capable of or will do.

> I would like to treat AU's as bricks that can be used to build courses (and blocks), however since the properties of these bricks aren't advertised it is difficult to use them.

I think this only applies in the case where someone is combining AUs completely in a vacuum (which IMO will be rare), and I think this is specifically when `CompletedOrPassed` should be used, and I think that's okay. We could certainly add a best practice that reads something like, "If the course author is unfamiliar with what the AU is capable of doing then it should set the `moveOn` to `CompletedOrPassed`".

> My understanding is that the spec expects the meaning decided by the AU author, I think that the AU author should be required to also decided what it means to pass a PDF or a video and if they can't think of a good definition then they should use the same definition as completed (or vice versa). I think it can be judged that you have watched enough of a video to pass it, in fact I think that this makes more sense than complete.

Right, and I agree, but I think by saying this you've proven my point that the AU author (or the author of the system that is going to generate the actual AUs) is going to know that and therefore will publish what the moveOn criteria needs to be set to at which point the AU author will know.

Ultimately I'm happy to discuss further, and I'm just expressing one opinion amongst many on the WG calls, but I think the set of moveOn possibilities covers this nicely. If the `Or` version didn't exist then I'd agree that would be a problem, but given it is there to act as a "catch all" so to speak, I don't know that a change is needed. The other option is to look at the consequences, if you specify that AUs must send both a completed and a passed then you've forced a requirement on to the AU that it has to do something such that there will then be less meaning to be understood from the actual output of the course. I think you'd end up with AUs setting completion when a passed has occurred to meet the requirement without the ability to then send completion when they feel it is actually completed (think material available after a quiz has happened). They'll need to make sure the AU has been satisfied at the point that the score is captured because otherwise they'll have upset users who bail after the quiz before hitting the end. Alternatively you'll have AUs sending passed as soon as hitting complete because they simply don't have anything they consider judged, i.e. the video/pdf example above (assuming you don't consider that to be judged). Generally I think most members of the group consider "judged" to be something that is scored, or is more interactive than just getting through content.

Remember, it is also often expected that a course will be made up of AUs that are purely content with something like a post assessment that is a different AU where the former is considered completed but not passed, with the latter being passed because it generates a score (though I agree it'll often have a completed). If all of these AUs always have to generate both statements then there is very little point in even having differentiated statements and we might as well just move to a "Satisfied" as the only thing captured.

Also, I think the primary reason to use cmi5 will be for xAPI data beyond the simple moveOn management statements which will mean people will need to understand even more what to expect from the AU, for instance what other profile data might be captured via cmi5 allowed statements, etc.

(Cheers, I do appreciate the discussion!)

**Comment by thomasturrell** [comment]
Thank you for your input, let's discuss verbally (possibly during the weekly working group call, however I suspect this issue is outside of the scope of project catapult).

I have started with a preposed solution when I should have started with the problem that I see.

The problem I see is, it is not possible to know what statements an AU sends because the AU is a blackbox. Changing the move on criteria of an AU in a course is potentially harmful because it could result in a course that cannot be satisfied.

The spec suggests that courses structure can be changed in the LMS and exported by the LMS.

> The LMS SHOULD implement a means to create, edit, and maintain course structures.
> The LMS SHOULD implement the export of the course data structure ...

It is my assumption that the person who edits the course structure in the LMS might not be the same person that created the course or AU's within that course.

BTW, I see no problem with someone changing the mastery score at a later date because it can never set it to something that prevents the course from being satisfied.

**Comment by thomasturrell** [comment]
> We could certainly add a best practice that reads something like, "If the course author is unfamiliar with what the AU is capable of doing then it should set the moveOn to CompletedOrPassed".

I have just noticed that something similar is already in the best practices section

> **Best Practice #10 - LMS Administrators should use caution when changing the moveOn property.**
> The AU may not have the capability of sending statements required by any moveOn value that was not in the original course structure. It is recommended that all changes to course structures after import be tested prior to learner assignment.

Sorry I didn't see this sooner.

I believe that it would be best practice if the LMS stores the moveOn criteria that is in the published AU metadata. This way the LMS can allow the LMS administrator to only set the moveOne criteria to a valid one. Does this sound reasonable?

**Comment by thomasturrell** [comment]
Just thinking aloud.

I have a nagging doubt in my mind about passed and completed statements coming from the AU which are then analysed by the LMS to see if the move on criteria has been met.

Maybe it would be better if the AU was only required to send the satisfied statement, that way the AU could override the moveOn criteria if it needed to (for example override passed and complete moveOn criteria if it only has a concept of passed).

**Comment by brianjmiller** [comment]
> BTW, I see no problem with someone changing the mastery score at a later date because it can never set it to something that prevents the course from being satisfied.

Is incorrect and suffers from the same issue. The only way for this to be the case is if we limited what the course editor can do to be only ever *lowering* the mastery score. Otherwise they could in theory set the mastery score to a value higher than the AU is capable of setting.

I think the bottom line is still that a course editor that doesn't understand the AU well enough to be able to safely edit the properties associated with it (and then doesn't test said edited course) just shouldn't do so.

As far as the AU sending satisfied, I find that mildly interesting though it does go against what has been previously discussed: https://github.com/AICC/CMI-5_Spec_Current/issues/567

*And* suffers from the lack of LMS control over when such a thing is marked as such (i.e. the client side grading problem). Perhaps that isn't an issue because of how the moveOn criteria work now based on statements received from the client, but it is a thing to consider.

**Comment by thomasturrell** [comment]
From my perspective I would like to move the complexity of passed, completed and moveOn away from the LMS and down to the AU because the AU has all the information it needs to decide if it can send the satisfied statement, The LMS would need to look all this up from multiple sources.

For instance if LMS receives a passed statement, it needs to query the course to see what the move on criteria is, then it needs to (potentially) query the LRS to see if the other relevant statement exists, only then can it send a satisfied statement.

> And suffers from the lack of LMS control over when such a thing is marked as such (i.e. the client side grading problem).

As you say this problem exists either way. It must have been discussed previously. I wonder if signed statements offer some kind of solution for this problem? The only problem is that the certificate would have to be embedded into the AU.

**Comment by thomasturrell** [comment]
@brianjmiller Anyway I feel I'm distracting you with this issue and I'm aware that you have a lot more important things to do with project catapult.

**Comment by MrBillMcDonald** [comment]
Reviewed in  cmi5 working group meeting (6/17/2022)

As per the discussion on issue #708 last week,  Completed and Passed verbs have distinct and different purposes, and requiring both defeats the purpose.

- Completed indicates that all material or experiences have been viewed by the learner.
- Passed indicates that the learner has been judged/assessed as mastering the learning objectives.
